-- 02 月度产值回顾_不含销售数据 报表

select 
    null as '编号',
    null as '公司名称',
    null as '所属项目',
    null as '项目状态',
    null as '工程状态',
    null as '是否存在停工缓建',
    null as '工程操盘方',
    null as '成本操盘方',
    null as '明源系统代码',
    null as '投管代码',
    null as '月度回顾月份',
    null as '累计开工比例',
    null as '累计销售比例',
    null as '产值信息_总建筑面积',
    null as '产值信息_已开工面积',
    null as '产值信息_停工缓建面积',
    null as '产值信息_总产值',
    null as '产值信息_已发生产值',
    null as '产值信息_待发生产值',
    null as '销售信息_总可售面积',
    null as '销售信息_已售面积',
    null as '销售信息_待售面积',
    null as '销售信息_总货值',
    null as '销售信息_已达预售形象货值',
    null as '销售信息_已售货值',
    null as '销售信息_待售货值',
    null as '付款信息_累计应付款',
    null as '付款信息_累计实付款',
    null as '付款信息_本月累计实付款',
    null as '付款信息_已达产值未付金额',
    null as '付款信息_应付未付金额',
    null as '付款信息_下月预估支付金额',
    null as '付款信息_年度资金计划',
    null as '付款信息_本年预估剩余支付金额',
    null as '楼栋产值盘点_楼栋名称',
    null as '楼栋产值盘点_建设状态',
    null as '楼栋产值盘点_建筑面积',
    null as '楼栋产值盘点_已售面积',
    null as '楼栋产值盘点_开工面积',
    null as '楼栋产值盘点_总产值',
    null as '楼栋产值盘点_项目盘点累计已完成产值',
    null as '楼栋产值盘点_待发生产值',
    null as '楼栋产值盘点_累计应付金额',
    null as '楼栋产值盘点_累计实付金额',
    null as '楼栋产值盘点_已达产值未付金额',
    null as '楼栋产值盘点_应付未付金额'
from  p_project p
inner join mybusinessunit  bu on p.buguid =bu.buguid
where  1=1 