select
    清洗时间,
    统计维度,
    公司,
    城市,
    片区,
    镇街,
    项目,
    外键关联,
    项目名称,
    产品,
    id,
    parentid,
    是否加背景色,
    isnull(成本单方,0) as 成本单方,
    isnull(累计签约单价,0) as 累计签约单价,
    isnull(累计签约面积,0) as 累计签约面积,
    isnull(累计签约金额,0) as 累计签约金额,
    isnull(累计销售净利润账面,0) as 累计销售净利润账面,
    isnull(累计销售净利率账面,0) as 累计销售净利率账面,
    isnull(股东利润分配,0) as 股东利润分配,
    isnull(股东利润预分配,0) as 股东利润预分配,
    isnull(未售均价,0) as 未售均价,
    isnull(未售面积,0) as 未售面积,
    isnull(未售货值,0) as 未售货值,
    isnull(未售签约净利润,0) as 未售签约净利润,
    isnull(未售签约净利率,0) as 未售签约净利率,
    isnull(本年签约单价,0) as 本年签约单价,
    isnull(本年签约面积,0) as 本年签约面积,
    isnull(本年签约金额,0) as 本年签约金额,
    isnull(本年销售净利润账面,0) as 本年销售净利润账面,
    isnull(本年销售净利率账面,0) as 本年销售净利率账面,
    isnull(本年预计可售均价,0) as 本年预计可售均价,
    isnull(本年预计可售面积,0) as 本年预计可售面积,
    isnull(本年预计可售货值,0) as 本年预计可售货值,
    isnull(本年预计签约净利润,0) as 本年预计签约净利润,
    isnull(本年预计净利率,0) as 本年预计净利率,
    isnull(预估全年可售均价,0) as 预估全年可售均价,
    isnull(预估全年签约面积,0) as 预估全年签约面积,
    isnull(预估全年签约金额,0) as 预估全年签约金额,
    isnull(预估全年销售毛利润账面,0) as 预估全年销售毛利润账面,
    isnull(预估全年净利率,0) as 预估全年净利率,
    isnull(剩余货值实际流速版均价,0) as 剩余货值实际流速版均价,
    isnull(剩余货值实际流速版签约面积,0) as 剩余货值实际流速版签约面积,
    isnull(剩余货值实际流速版签约金额,0) as 剩余货值实际流速版签约金额,
    isnull(剩余货值实际流速版净利润,0) as 剩余货值实际流速版净利润,
    isnull(剩余货值实际流速版净利率,0) as 剩余货值实际流速版净利率,
    isnull(往年签约本年退房可售均价,0) as 往年签约本年退房可售均价,
    isnull(往年签约本年退房签约面积,0) as 往年签约本年退房签约面积,
    isnull(往年签约本年退房签约金额,0) as 往年签约本年退房签约金额,
    isnull(往年签约本年退房销售毛利润账面,0) as 往年签约本年退房销售毛利润账面,
    isnull(往年签约本年退房净利率,0) as 往年签约本年退房净利率,
    isnull(本年预估全年签约预警,0) as 本年预估全年签约预警,
    isnull(全盘剩余货值实际流速版预警,0) as 全盘剩余货值实际流速版预警,
    isnull(本月签约单价,0) as 本月签约单价,
    isnull(本月签约面积,0) as 本月签约面积,
    isnull(本月签约金额,0) as 本月签约金额,
    isnull(本月净利润签约,0) as 本月净利润签约,
    isnull(本月销售净利率账面,0) as 本月销售净利率账面,
    isnull(本月认购单价,0) as 本月认购单价,
    isnull(本月认购面积,0) as 本月认购面积,
    isnull(本月认购金额,0) as 本月认购金额,
    isnull(本月认购净利润账面,0) as 本月认购净利润账面,
    isnull(本月认购净利率账面,0) as 本月认购净利率账面,
    isnull(整盘可售单价,0) as 整盘可售单价,
    isnull(整盘可售面积,0) as 整盘可售面积,
    isnull(整盘可售货值,0) as 整盘可售货值,
    isnull(整盘可售净利润账面,0) as 整盘可售净利润账面,
    isnull(整盘可售净利率账面,0) as 整盘可售净利率账面,
    isnull(自持面积,0) as 自持面积,
    isnull(留置比例,0) as 留置比例,
    isnull(固定资产,0) as 固定资产,
    isnull(整盘合计税后利润,0)  as 整盘合计税后利润, 
    isnull(整盘合计税后利润,0)- isnull(固定资产,0) as 整盘可售净利润账面_整盘合计,
case when 项目名称 = '项目汇总' then 0 when 项目名称 = '新增量' then 1 when 项目名称 = '增量' then 2
when 项目名称 = '存量' then 3 else 99 end 排序,
case when pj.projguid is  null or 是否加背景色 = 1 then 0 else 1 end as 是否过滤--项目层级去掉项目数据，只保留项目汇总数据
from wqzydtBi_saleProfitinfo t
left join data_wide_dws_mdm_project pj on t.外键关联 = pj.spreadname
where isnull(累计签约金额,0)<>0 or isnull(未售货值,0)<> 0 or isnull(整盘可售货值,0)<>0 or isnull(固定资产,0)<>0 or isnull(留置比例,0)<> 0
and datediff(year,清洗时间,getdate()) = 0