-- 投管系统表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('mdm_GCBuild')) ,0))>0 BEGIN ALTER TABLE mdm_GCBuild disable CHANGE_TRACKING END ;

-- 销售系统表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_Building')) ,0))>0 BEGIN ALTER TABLE p_Building disable CHANGE_TRACKING END ;

-- 客服系统表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('k_ProviderProjectConstru')) ,0))>0 BEGIN ALTER TABLE k_ProviderProjectConstru disable CHANGE_TRACKING END ;


