-- 投管系统表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('mdm_GCBuild')) ,0))=0 BEGIN ALTER TABLE mdm_GCBuild ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;

-- 销售系统表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_Building')) ,0))=0 BEGIN ALTER TABLE p_Building ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;

-- 客服系统表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('k_ProviderProjectConstru')) ,0))=0 BEGIN ALTER TABLE k_ProviderProjectConstru ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;



