-- 基础数据表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_GCBuild')) ,0))>0 BEGIN ALTER TABLE md_GCBuild disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_GCBuild_Work')) ,0))>0 BEGIN ALTER TABLE md_GCBuild_Work disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_product_Work')) ,0))>0 BEGIN ALTER TABLE md_product_Work disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_product')) ,0))>0 BEGIN ALTER TABLE md_product disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_ProductDtl_Work')) ,0))>0 BEGIN ALTER TABLE md_ProductDtl_Work disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_ProductDtl')) ,0))>0 BEGIN ALTER TABLE md_ProductDtl disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_ProductBuild_Work')) ,0))>0 BEGIN ALTER TABLE md_ProductBuild_Work disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_ProductBuild')) ,0))>0 BEGIN ALTER TABLE md_ProductBuild disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_BuildHoldRate')) ,0))>0 BEGIN ALTER TABLE md_BuildHoldRate disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_BuildZxRate')) ,0))>0 BEGIN ALTER TABLE md_BuildZxRate disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_BuildIndex')) ,0))>0 BEGIN ALTER TABLE md_BuildIndex disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_BuildZSArea')) ,0))>0 BEGIN ALTER TABLE md_BuildZSArea disable CHANGE_TRACKING END ;

-- POM系统表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_HkbBiddingSectionWork')) ,0))>0 BEGIN ALTER TABLE p_HkbBiddingSectionWork disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_HkbBiddingBuildingWork')) ,0))>0 BEGIN ALTER TABLE p_HkbBiddingBuildingWork disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_HkbBiddingBuilding2BuildingWork')) ,0))>0 BEGIN ALTER TABLE p_HkbBiddingBuilding2BuildingWork disable CHANGE_TRACKING END ;

-- 计划系统表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_BiddingBuilding')) ,0))>0 BEGIN ALTER TABLE p_BiddingBuilding disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_BiddingSection')) ,0))>0 BEGIN ALTER TABLE p_BiddingSection disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('ys_SpecialBusinessUnit')) ,0))>0 BEGIN ALTER TABLE ys_SpecialBusinessUnit disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanCompile')) ,0))>0 BEGIN ALTER TABLE jd_ProjectPlanCompile disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanExecute')) ,0))>0 BEGIN ALTER TABLE jd_ProjectPlanExecute disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanExecuteHistory')) ,0))>0 BEGIN ALTER TABLE jd_ProjectPlanExecuteHistory disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanTaskCompile')) ,0))>0 BEGIN ALTER TABLE jd_ProjectPlanTaskCompile disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanTaskExecute')) ,0))>0 BEGIN ALTER TABLE jd_ProjectPlanTaskExecute disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanTaskExecuteHistory')) ,0))>0 BEGIN ALTER TABLE jd_ProjectPlanTaskExecuteHistory disable CHANGE_TRACKING END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_TaskReport')) ,0))>0 BEGIN ALTER TABLE jd_TaskReport disable CHANGE_TRACKING END ;

-- 合同表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('cb_Contract')) ,0))>0 BEGIN ALTER TABLE cb_Contract disable CHANGE_TRACKING END ;