--352数据库
--禁用触发器
ALTER TABLE md_GCBuild DISABLE TRIGGER ALL;
ALTER TABLE md_product DISABLE TRIGGER ALL;
ALTER TABLE md_ProductDtl DISABLE TRIGGER ALL;
ALTER TABLE md_ProductBuild DISABLE TRIGGER ALL;
ALTER TABLE p_HkbBiddingBuilding2BuildingWork DISABLE TRIGGER ALL;
ALTER TABLE jd_ProjectPlanExecute DISABLE TRIGGER ALL;
ALTER TABLE jd_ProjectPlanTaskExecute DISABLE TRIGGER ALL;
ALTER TABLE jd_TaskReport DISABLE TRIGGER ALL;
ALTER TABLE cb_Contract DISABLE TRIGGER ALL;


