-- 基础数据表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_GCBuild')) ,0))=0 BEGIN ALTER TABLE md_GCBuild ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_GCBuild_Work')) ,0))=0 BEGIN ALTER TABLE md_GCBuild_Work ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_product_Work')) ,0))=0 BEGIN ALTER TABLE md_product_Work ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_product')) ,0))=0 BEGIN ALTER TABLE md_product ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_ProductDtl_Work')) ,0))=0 BEGIN ALTER TABLE md_ProductDtl_Work ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_ProductDtl')) ,0))=0 BEGIN ALTER TABLE md_ProductDtl ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_ProductBuild_Work')) ,0))=0 BEGIN ALTER TABLE md_ProductBuild_Work ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_ProductBuild')) ,0))=0 BEGIN ALTER TABLE md_ProductBuild ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_BuildHoldRate')) ,0))=0 BEGIN ALTER TABLE md_BuildHoldRate ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_BuildZxRate')) ,0))=0 BEGIN ALTER TABLE md_BuildZxRate ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_BuildIndex')) ,0))=0 BEGIN ALTER TABLE md_BuildIndex ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('md_BuildZSArea')) ,0))=0 BEGIN ALTER TABLE md_BuildZSArea ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;

-- POM系统表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_HkbBiddingSectionWork')) ,0))=0 BEGIN ALTER TABLE p_HkbBiddingSectionWork ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_HkbBiddingBuildingWork')) ,0))=0 BEGIN ALTER TABLE p_HkbBiddingBuildingWork ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_HkbBiddingBuilding2BuildingWork')) ,0))=0 BEGIN ALTER TABLE p_HkbBiddingBuilding2BuildingWork ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;

-- 计划系统表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_BiddingBuilding')) ,0))=0 BEGIN ALTER TABLE p_BiddingBuilding ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_BiddingSection')) ,0))=0 BEGIN ALTER TABLE p_BiddingSection ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('ys_SpecialBusinessUnit')) ,0))=0 BEGIN ALTER TABLE ys_SpecialBusinessUnit ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanCompile')) ,0))=0 BEGIN ALTER TABLE jd_ProjectPlanCompile ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanExecute')) ,0))=0 BEGIN ALTER TABLE jd_ProjectPlanExecute ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanExecuteHistory')) ,0))=0 BEGIN ALTER TABLE jd_ProjectPlanExecuteHistory ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanTaskCompile')) ,0))=0 BEGIN ALTER TABLE jd_ProjectPlanTaskCompile ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanTaskExecute')) ,0))=0 BEGIN ALTER TABLE jd_ProjectPlanTaskExecute ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_ProjectPlanTaskExecuteHistory')) ,0))=0 BEGIN ALTER TABLE jd_ProjectPlanTaskExecuteHistory ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('jd_TaskReport')) ,0))=0 BEGIN ALTER TABLE jd_TaskReport ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;

-- 合同表
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('cb_Contract')) ,0))=0 BEGIN ALTER TABLE cb_Contract ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ;