--352数据库
--禁用触发器
ALTER TABLE md_GCBuild ENABLE TRIGGER ALL;
ALTER TABLE md_product ENABLE TRIGGER ALL;
ALTER TABLE md_ProductDtl ENABLE TRIGGER ALL;
ALTER TABLE md_ProductBuild ENABLE TRIGGER ALL;
ALTER TABLE p_HkbBiddingBuilding2BuildingWork ENABLE TRIGGER ALL;
ALTER TABLE jd_ProjectPlanExecute ENABLE TRIGGER ALL;
ALTER TABLE jd_ProjectPlanTaskExecute ENABLE TRIGGER ALL;
ALTER TABLE jd_TaskReport ENABLE TRIGGER ALL;
ALTER TABLE cb_Contract ENABLE TRIGGER ALL;


