--材料数据库
--禁用CT
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('myWorkflowNodeEntity')) ,0))>0 BEGIN ALTER TABLE myWorkflowNodeEntity disable CHANGE_TRACKING END ; 
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_TaskWake')) ,0))>0 BEGIN ALTER TABLE p_TaskWake disable CHANGE_TRACKING END ; 
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('myWorkflowProcessEntity')) ,0))>0 BEGIN ALTER TABLE myWorkflowProcessEntity disable CHANGE_TRACKING END ; 
