--材料数据库
--开启CT
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('myWorkflowNodeEntity')) ,0))=0 BEGIN ALTER TABLE myWorkflowNodeEntity ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ; 
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('p_TaskWake')) ,0))=0 BEGIN ALTER TABLE p_TaskWake ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ; 
IF (SELECT ISNULL( CHANGE_TRACKING_MIN_VALID_VERSION( OBJECT_ID('myWorkflowProcessEntity')) ,0))=0 BEGIN ALTER TABLE myWorkflowProcessEntity ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON) END ; 
