 --2025-07-23 新增的大户型、产成品、联动房字段
--  declare @var_date datetime =getdate();
--  DECLARE @var_projguid varchar(50) ='9CEDEF9B-5D32-E811-80BA-E61F13C57837';

WITH Sale AS (SELECT    投管编码 AS 项目代码 ,
                        区域 AS 公司事业部 ,
                        营销片区 AS 组团 ,
                        项目GUID ,
                        项目名称 AS 项目名称 ,
                        项目负责人 AS 营销经理 ,
                        存量增量 AS 项目获取状态 ,
                        城市 AS 城市 ,
                        SUM(ISNULL(本年任务, 0)) AS 年度任务 ,
                        SUM(CASE WHEN 业态 ='住宅' THEN ISNULL(本年任务, 0)ELSE 0 END) AS 年度住宅类任务 ,
                        SUM(CASE WHEN 业态 ='商办' THEN ISNULL(本年任务, 0)ELSE 0 END) AS 年度商办任务 ,
                        SUM(CASE WHEN 产品类型 IN ('写字楼') THEN ISNULL(本年任务, 0)ELSE 0 END) AS 年度写字楼任务 ,
                        SUM(CASE WHEN 产品类型 IN ('公寓') THEN ISNULL(本年任务, 0)ELSE 0 END) AS 年度公寓任务 ,
                        SUM(CASE WHEN 产品类型 IN ('商墅') THEN ISNULL(本年任务, 0)ELSE 0 END) AS 年度商墅任务 ,
                        SUM(CASE WHEN 产品类型 IN ('商铺') THEN ISNULL(本年任务, 0)ELSE 0 END) AS 年度商铺任务 ,
                        SUM(CASE WHEN 业态='车位' THEN ISNULL(本年任务, 0)ELSE 0 END) AS 年度车位任务 ,
                        SUM(ISNULL(本年产成品任务, 0)) + sum(isnull(准产成品年度任务,0)) AS 年度产成品任务 ,
                        SUM(ISNULL(本月任务, 0)) AS 签约任务月度 ,
                        SUM(CASE WHEN 产品类型 IN ('住宅', '高级住宅') THEN ISNULL(本月任务, 0)ELSE 0 END) AS 住宅类月度任务 ,
                        SUM(CASE WHEN 业态 ='商办' THEN ISNULL(本月任务, 0)ELSE 0 END) AS 商办月度任务 ,
                        SUM(CASE WHEN 产品类型 IN ('写字楼') THEN ISNULL(本月任务, 0)ELSE 0 END) AS 月度写字楼任务 ,
                        SUM(CASE WHEN 产品类型 IN ('公寓') THEN ISNULL(本月任务, 0)ELSE 0 END) AS 月度公寓任务 ,
                        SUM(CASE WHEN 产品类型 IN ('商墅') THEN ISNULL(本月任务, 0)ELSE 0 END)  AS 月度商墅任务 ,
                        SUM(CASE WHEN 产品类型 IN ('商铺') THEN ISNULL(本月任务, 0)ELSE 0 END)  AS 月度商铺任务 ,
                        SUM(CASE WHEN 业态='车位' THEN ISNULL(本月任务, 0)ELSE 0 END)  AS 车位签约月度任务 ,
                        SUM(ISNULL(本月产成品任务, 0)) + sum(isnull(准产成品月度任务,0)) AS 产成品月度任务 ,
                        --NULL AS 本日来访 ,
                        --NULL AS 本月到访 ,
                        SUM(case  when  业态 <> '车位' THEN  ISNULL(本日认购套数,0) else  0 end ) AS 本日认购套数非车位 ,
                        SUM(ISNULL(本日认购面积,0)) AS 本日认购面积 ,
                        SUM(ISNULL(本日认购金额,0)) AS 本日认购金额 ,
                        SUM(ISNULL(本日签约套数,0)) AS 本日签约套数 ,
                        SUM(ISNULL(本日签约面积,0)) AS 本日签约面积 ,
                        SUM(ISNULL(本日签约金额, 0)) AS 本日签约金额 ,
                        SUM(ISNULL(本周认购套数, 0)) AS 本周认购套数 ,
                        SUM(ISNULL(本周认购面积,0)) AS 本周认购面积 ,
                        SUM(ISNULL(本周认购金额, 0)) AS 本周认购金额 ,
                        SUM(ISNULL(本周签约套数, 0)) AS 本周签约套数 ,
                        SUM(ISNULL(本周签约面积, 0)) AS 本周签约面积 ,
                        SUM(ISNULL(本周签约金额, 0)) AS 本周签约金额 ,
                        SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(本月认购套数, 0)ELSE 0 END) AS 本月认购套数非车位 ,
                        SUM(ISNULL(本月认购面积, 0)) AS 本月认购面积 ,
                        SUM(ISNULL(本月认购金额, 0)) AS 本月认购金额 ,
                        SUM(ISNULL(本月签约套数, 0)) AS 本月签约套数 ,
                        SUM(ISNULL(本月签约面积, 0)) AS 本月签约面积 ,
                        SUM(ISNULL(本月签约金额, 0)) AS 本月签约金额 ,
                        SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(其他业绩本月认购套数, 0) else 0 end) AS 本月重售认购套数非车位 ,
                        SUM(ISNULL(其他业绩本月认购面积, 0)) AS 本月重售认购面积 ,
                        SUM(ISNULL(其他业绩本月认购金额, 0)) AS 本月重售认购金额 ,
                        SUM(ISNULL(其他业绩本月签约套数, 0)) AS 本月重售签约套数 ,
                        SUM(ISNULL(其他业绩本月签约面积, 0)) AS 本月重售签约面积 ,
                        SUM(ISNULL(其他业绩本月签约金额, 0)) AS 本月重售签约金额 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本月认购套数, 0)ELSE 0 END) AS 本月住宅认购套数 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本月认购面积, 0)ELSE 0 END) AS 本月住宅认购面积 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本月认购金额, 0)ELSE 0 END) AS 本月住宅认购金额 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本月签约套数, 0)ELSE 0 END) AS 本月住宅签约套数 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本月签约面积, 0)ELSE 0 END) AS 本月住宅签约面积 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本月签约金额, 0)ELSE 0 END) AS 本月住宅签约金额 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(其他业绩本月签约套数, 0)ELSE 0 END) AS 本月住宅重售签约套数 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(其他业绩本月签约面积, 0)ELSE 0 END) AS 本月住宅重售签约面积 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(其他业绩本月签约金额, 0)ELSE 0 END) AS 本月住宅重售签约金额 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本月认购套数, 0) ELSE 0 END) AS 本月商办认购套数 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本月认购面积, 0) ELSE 0 END) AS 本月商办认购面积 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本月认购金额, 0)ELSE 0 END) AS 本月商办认购金额 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本月签约套数, 0)ELSE 0 END) AS 本月商办签约套数 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本月签约面积, 0)ELSE 0 END)  AS 本月商办签约面积 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本月签约金额, 0)ELSE 0 END) AS 本月商办签约金额 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(其他业绩本月签约套数, 0)ELSE 0 END) AS 本月商办重售签约套数 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(其他业绩本月签约面积, 0)ELSE 0 END) AS 本月商办重售签约面积 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(其他业绩本月签约金额, 0)ELSE 0 END) AS 本月商办重售签约金额 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本月认购套数, 0)ELSE 0 END) AS 本月车位认购套数 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本月认购面积, 0)ELSE 0 END) AS 本月车位认购面积 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本月认购金额, 0)ELSE 0 END) AS 本月车位认购金额 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本月签约套数, 0)ELSE 0 END) AS 本月车位签约套数 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本月签约面积, 0)ELSE 0 END)  AS 本月车位签约面积 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本月签约金额, 0)ELSE 0 END) AS 本月车位签约金额 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(其他业绩本月签约套数, 0)ELSE 0 END) AS 本月车位重售签约套数 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(其他业绩本月签约面积, 0)ELSE 0 END) AS 本月车位重售签约面积 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(其他业绩本月签约金额, 0)ELSE 0 END) AS 本月车位重售签约金额 ,

                        
                        SUM(ISNULL(已认购未签约套数, 0)) AS 已认购未签约签约套数 ,
                        SUM(ISNULL(已认购未签约签约面积 , 0)) AS 已认购未签约签约面积 ,
                        SUM(ISNULL(已认购未签约金额, 0)) AS 已认购未签约签约金额 ,
                        SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(本年认购套数, 0)ELSE 0 END) AS 本年认购套数非车位 ,
                        SUM(ISNULL(本年认购面积,0)) AS 本年认购面积 ,
                        SUM(ISNULL(本年认购金额,0)) AS 本年认购金额 ,
                        SUM(ISNULL(本年签约套数,0)) AS 本年签约套数 ,
                        SUM(ISNULL(本年签约面积,0)) AS 本年签约面积 ,
                        SUM(ISNULL(本年签约金额,0)) AS 本年签约金额 ,
                        SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(其他业绩本年认购套数, 0) else 0 end ) AS 本年重售认购套数非车位 ,
                        SUM(ISNULL(其他业绩本年认购面积, 0)) AS 本年重售认购面积 ,
                        SUM(ISNULL(其他业绩本年认购金额, 0)) AS 本年重售认购金额 ,
                        SUM(ISNULL(其他业绩本年签约套数, 0)) AS 本年重售签约套数 ,
                        SUM(ISNULL(其他业绩本年签约面积,0)) AS 本年重售签约面积 ,
                        SUM(ISNULL(其他业绩本年签约金额, 0)) AS 本年重售签约金额 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本年认购套数, 0)ELSE 0 END) AS 本年住宅认购套数 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本年认购面积, 0)ELSE 0 END) AS 本年住宅认购面积 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本年认购金额, 0)ELSE 0 END) AS 本年住宅认购金额 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本年签约套数, 0)ELSE 0 END) AS 本年住宅签约套数 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本年签约面积, 0)ELSE 0 END) AS 本年住宅签约面积 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(本年签约金额, 0)ELSE 0 END) AS 本年住宅签约金额 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(其他业绩本年签约套数, 0)ELSE 0 END) AS 本年住宅重售签约套数 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(其他业绩本年签约套数, 0)ELSE 0 END) AS 本年住宅重售签约面积 ,
                        SUM(CASE WHEN 业态 = '住宅' THEN ISNULL(其他业绩本年签约金额, 0)ELSE 0 END) AS 本年住宅重售签约金额 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本年认购套数, 0)ELSE 0 END) AS 本年商办认购套数 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本年认购面积, 0)ELSE 0 END) AS 本年商办认购面积 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本年认购金额, 0)ELSE 0 END) AS 本年商办认购金额 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本年签约套数, 0)ELSE 0 END) AS 本年商办签约套数 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本年签约面积, 0)ELSE 0 END) AS 本年商办签约面积 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(本年签约金额, 0)ELSE 0 END) AS 本年商办签约金额 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(其他业绩本年签约套数, 0)ELSE 0 END) AS 本年商办重售签约套数 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(其他业绩本年签约面积, 0)ELSE 0 END) AS 本年商办重售签约面积 ,
                        SUM(CASE WHEN 业态 = '商办' THEN ISNULL(其他业绩本年签约金额, 0)ELSE 0 END) AS 本年商办重售签约金额 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本年认购套数, 0)ELSE 0 END) AS 本年车位认购套数 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本年认购面积, 0)ELSE 0 END) AS 本年车位认购面积 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本年认购金额, 0)ELSE 0 END) AS 本年车位认购金额 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本年签约套数, 0)ELSE 0 END) AS 本年车位签约套数 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本年签约面积, 0)ELSE 0 END) AS 本年车位签约面积 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(本年签约金额, 0)ELSE 0 END) AS 本年车位签约金额 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(其他业绩本年签约套数, 0)ELSE 0 END) AS 本年车位重售签约套数 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(其他业绩本年签约面积, 0)ELSE 0 END) AS 本年车位重售签约面积 ,
                        SUM(CASE WHEN 业态 = '车位' THEN ISNULL(其他业绩本年签约金额, 0)ELSE 0 END) AS 本年车位重售签约金额 ,


                        -- 产成品本月
                        SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(本月产成品认购套数, 0)ELSE 0 END)  
                            + SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(本月准产成品认购套数, 0)ELSE 0 END) AS 本月产成品认购套数非车位 ,
                        SUM(ISNULL(本月产成品认购面积, 0))+ SUM(ISNULL(本月准产成品认购面积, 0)) AS 本月产成品认购面积 ,
                        SUM(ISNULL(本月产成品认购金额, 0)) + SUM(ISNULL(本月准产成品认购金额, 0)) AS 本月产成品认购金额 ,
                        SUM(ISNULL(本月产成品签约套数, 0)) + SUM(ISNULL(本月准产成品签约套数, 0)) AS 本月产成品签约套数 ,
                        SUM(ISNULL(本月产成品签约面积, 0)) + SUM(ISNULL(本月准产成品签约面积, 0)) AS 本月产成品签约面积 ,
                        SUM(ISNULL(本月产成品签约金额, 0)) + SUM(ISNULL(本月准产成品签约金额, 0)) AS 本月产成品签约金额 ,
                        SUM(ISNULL(其他业绩产成品本月签约套数, 0)) + SUM(ISNULL(其他业绩准产成品本月签约套数, 0)) AS 本月产成品重售签约套数 ,
                        SUM(ISNULL(其他业绩产成品本月签约面积, 0)) + SUM(ISNULL(其他业绩准产成品本月签约面积, 0)) AS 本月产成品重售签约面积 ,
                        SUM(ISNULL(其他业绩产成品本月签约金额, 0)) + SUM(ISNULL(其他业绩准产成品本月签约金额, 0)) AS 本月产成品重售签约金额 ,

                        SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(本年产成品认购套数, 0)ELSE 0 END)
                          + SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(本年准产成品认购套数, 0)ELSE 0 END) AS 本年产成品认购套数非车位 ,
                        SUM(ISNULL(本年产成品认购面积, 0)) + SUM(ISNULL(本年准产成品认购面积, 0)) AS 本年产成品认购面积 ,
                        SUM(ISNULL(本年产成品认购金额, 0)) + SUM(ISNULL(本年准产成品认购金额, 0)) AS 本年产成品认购金额 ,
                        SUM(ISNULL(本年产成品签约套数, 0)) + SUM(ISNULL(本年准产成品签约套数, 0)) AS 本年产成品签约套数 ,
                        SUM(ISNULL(本年产成品签约面积, 0)) + SUM(ISNULL(本年准产成品签约面积, 0)) AS 本年产成品签约面积 ,
                        SUM(ISNULL(本年产成品签约金额, 0)) + SUM(ISNULL(本年准产成品签约金额, 0)) AS 本年产成品签约金额 ,
                        SUM(ISNULL(其他业绩产成品本年签约套数, 0)) + SUM(ISNULL(其他业绩准产成品本年签约套数, 0)) AS 本年产成品重售签约套数 ,
                        SUM(ISNULL(其他业绩产成品本年签约面积, 0)) + SUM(ISNULL(其他业绩准产成品本年签约面积, 0)) AS 本年产成品重售签约面积 ,
                        SUM(ISNULL(其他业绩产成品本年签约金额, 0)) + SUM(ISNULL(其他业绩准产成品本年签约金额, 0)) AS 本年产成品重售签约金额 ,


                        -- 现产成品本月
                        SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(本月产成品认购套数, 0)ELSE 0 END) AS 本月现产成品认购套数非车位 ,
                        SUM(ISNULL(本月产成品认购面积, 0)) AS 本月现产成品认购面积 ,
                        SUM(ISNULL(本月产成品认购金额, 0)) AS 本月现产成品认购金额 ,
                        SUM(ISNULL(本月产成品签约套数, 0)) AS 本月现产成品签约套数 ,
                        SUM(ISNULL(本月产成品签约面积, 0)) AS 本月现产成品签约面积 ,
                        SUM(ISNULL(本月产成品签约金额, 0)) AS 本月现产成品签约金额 ,
                        SUM(ISNULL(其他业绩产成品本月签约套数, 0)) AS 本月现产成品重售签约套数 ,
                        SUM(ISNULL(其他业绩产成品本月签约面积, 0)) AS 本月现产成品重售签约面积 ,
                        SUM(ISNULL(其他业绩产成品本月签约金额, 0)) AS 本月现产成品重售签约金额 ,

                        SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(本年产成品认购套数, 0)ELSE 0 END) AS 本年现产成品认购套数非车位 ,
                        SUM(ISNULL(本年产成品认购面积, 0)) AS 本年现产成品认购面积 ,
                        SUM(ISNULL(本年产成品认购金额, 0)) AS 本年现产成品认购金额 ,
                        SUM(ISNULL(本年产成品签约套数, 0)) AS 本年现产成品签约套数 ,
                        SUM(ISNULL(本年产成品签约面积, 0)) AS 本年现产成品签约面积 ,
                        SUM(ISNULL(本年产成品签约金额, 0)) AS 本年现产成品签约金额 ,
                        SUM(ISNULL(其他业绩产成品本年签约套数, 0)) AS 本年现产成品重售签约套数 ,
                        SUM(ISNULL(其他业绩产成品本年签约面积, 0)) AS 本年现产成品重售签约面积 ,
                        SUM(ISNULL(其他业绩产成品本年签约金额, 0)) AS 本年现产成品重售签约金额 ,   
                
                        -- 准产成品本月
                        SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(本月准产成品认购套数, 0)ELSE 0 END) AS 本月准产成品认购套数非车位 ,
                        SUM(ISNULL(本月准产成品认购面积, 0)) AS 本月准产成品认购面积 ,
                        SUM(ISNULL(本月准产成品认购金额, 0)) AS 本月准产成品认购金额 ,
                        SUM(ISNULL(本月准产成品签约套数, 0)) AS 本月准产成品签约套数 ,
                        SUM(ISNULL(本月准产成品签约面积, 0)) AS 本月准产成品签约面积 ,
                        SUM(ISNULL(本月准产成品签约金额, 0)) AS 本月准产成品签约金额 ,
                        SUM(ISNULL(其他业绩准产成品本月签约套数, 0)) AS 本月准产成品重售签约套数 ,
                        SUM(ISNULL(其他业绩准产成品本月签约面积, 0)) AS 本月准产成品重售签约面积 ,
                        SUM(ISNULL(其他业绩准产成品本月签约金额, 0)) AS 本月准产成品重售签约金额 ,

                        SUM(CASE WHEN 业态 <> '车位' THEN ISNULL(本年准产成品认购套数, 0)ELSE 0 END) AS 本年准产成品认购套数非车位 ,
                        SUM(ISNULL(本年准产成品认购面积, 0)) AS 本年准产成品认购面积 ,
                        SUM(ISNULL(本年准产成品认购金额, 0)) AS 本年准产成品认购金额 ,
                        SUM(ISNULL(本年准产成品签约套数, 0)) AS 本年准产成品签约套数 ,
                        SUM(ISNULL(本年准产成品签约面积, 0)) AS 本年准产成品签约面积 ,
                        SUM(ISNULL(本年准产成品签约金额, 0)) AS 本年准产成品签约金额 ,
                        SUM(ISNULL(其他业绩准产成品本年签约套数, 0)) AS 本年准产成品重售签约套数 ,
                        SUM(ISNULL(其他业绩准产成品本年签约面积, 0)) AS 本年准产成品重售签约面积 ,
                        SUM(ISNULL(其他业绩准产成品本年签约金额, 0)) AS 本年准产成品重售签约金额 ,   

                        --大户型
                        sum(isnull(本日大户型认购金额,0)) as 本日大户型认购金额 ,
                        sum(isnull(本日大户型认购面积,0)) as 本日大户型认购面积,
                        sum(isnull(本日大户型认购套数,0)) as 本日大户型认购套数,
                        sum(isnull(本日大户型签约金额,0)) as 本日大户型签约金额,
                        sum(isnull(本日大户型签约面积,0)) as 本日大户型签约面积,
                        sum(isnull(本日大户型签约套数,0)) as 本日大户型签约套数,

                        sum(isnull(本周大户型认购金额,0)) as 本周大户型认购金额,
                        sum(isnull(本周大户型认购面积,0)) as 本周大户型认购面积,
                        sum(isnull(本周大户型认购套数,0)) as 本周大户型认购套数,
                        sum(isnull(本周大户型签约金额,0)) as 本周大户型签约金额,
                        sum(isnull(本周大户型签约面积,0)) as 本周大户型签约面积,
                        sum(isnull(本周大户型签约套数,0)) as 本周大户型签约套数,

                        sum(isnull(本月大户型认购金额,0)) as 本月大户型认购金额,
                        sum(isnull(本月大户型认购面积,0)) as 本月大户型认购面积,
                        sum(isnull(本月大户型认购套数,0)) as 本月大户型认购套数,
                        sum(isnull(本月大户型签约金额,0)) as 本月大户型签约金额,
                        sum(isnull(本月大户型签约面积,0)) as 本月大户型签约面积,
                        sum(isnull(本月大户型签约套数,0)) as 本月大户型签约套数,

                        sum(isnull(本年大户型认购金额,0)) as 本年大户型认购金额,
                        sum(isnull(本年大户型认购面积,0)) as 本年大户型认购面积,
                        sum(isnull(本年大户型认购套数,0)) as 本年大户型认购套数,
                        sum(isnull(本年大户型签约金额,0)) as 本年大户型签约金额,
                        sum(isnull(本年大户型签约面积,0)) as 本年大户型签约面积,
                        sum(isnull(本年大户型签约套数,0)) as 本年大户型签约套数,

                        -- 联动房
                        sum(isnull(本日联动房认购金额,0)) as 本日联动房认购金额,
                        sum(isnull(本日联动房认购面积,0)) as 本日联动房认购面积,
                        sum(isnull(本日联动房认购套数,0)) as 本日联动房认购套数,
                        sum(isnull(本日联动房签约金额,0)) as 本日联动房签约金额,
                        sum(isnull(本日联动房签约面积,0)) as 本日联动房签约面积,
                        sum(isnull(本日联动房签约套数,0)) as  本日联动房签约套数,

                        sum(isnull(本周联动房认购金额,0)) as 本周联动房认购金额,
                        sum(isnull(本周联动房认购面积,0)) as 本周联动房认购面积,
                        sum(isnull(本周联动房认购套数,0)) as 本周联动房认购套数,
                        sum(isnull(本周联动房签约金额,0)) as 本周联动房签约金额,
                        sum(isnull(本周联动房签约面积,0)) as 本周联动房签约面积, 
                        sum(isnull(本周联动房签约套数,0)) as 本周联动房签约套数,

                        sum(isnull(本月联动房认购金额,0)) as 本月联动房认购金额,
                        sum(isnull(本月联动房认购面积,0)) as 本月联动房认购面积,
                        sum(isnull(本月联动房认购套数,0)) as 本月联动房认购套数,
                        sum(isnull(本月联动房签约金额,0)) as 本月联动房签约金额,
                        sum(isnull(本月联动房签约面积,0)) as 本月联动房签约面积,
                        sum(isnull(本月联动房签约套数,0)) as 本月联动房签约套数,

                        sum(isnull(本年联动房认购金额,0)) as 本年联动房认购金额,
                        sum(isnull(本年联动房认购面积,0)) as 本年联动房认购面积,
                        sum(isnull(本年联动房认购套数,0)) as 本年联动房认购套数,
                        sum(isnull(本年联动房签约金额,0)) as 本年联动房签约金额,
                        sum(isnull(本年联动房签约面积,0)) as 本年联动房签约面积,
                        sum(isnull(本年联动房签约套数,0)) as 本年联动房签约套数,

                        sum(isnull(本月产成品任务,0)) as 本月现产成品任务,
                        sum(isnull(本年产成品任务,0)) as 本年现产成品任务,
                        sum(isnull([准产成品月度任务],0)) as 本月准产成品任务,
                        sum(isnull([准产成品年度任务],0)) as 本年准产成品任务,
                        sum(isnull([大户型月度任务],0)) as 大户型月度任务,
                        sum(isnull([大户型年度任务],0)) as 大户型年度任务
                     FROM   [172.16.4.161].highdata_prod.dbo.[s_hnyxxp_projSaleNew] sale with(nolock)
                     WHERE  sale.层级 = '项目' AND  层级名称 = '全部项目' AND   DATEDIFF(DAY, 数据清洗日期, @var_date) = 0
                            and  sale.层级名称显示<>'平衡处理'
					 and  sale.项目GUID in (@var_projguid)
              GROUP BY 投管编码 ,
                       区域 ,
                       营销片区 ,
                       项目GUID ,
                       项目名称 ,
                       项目负责人 ,
                       存量增量 ,
                       城市) ,
-- 来访数据
     lf AS  (
	        SELECT  p.ProjGUID AS 项目GUID, 
			SUM(CASE WHEN DATEDIFF(day,bizdate,@var_date) =0  THEN   ISNULL([newVisitNum], 0) + ISNULL([oldVisitNum], 0) ELSE  0 END ) AS 本日来访,
                        SUM(CASE WHEN DATEDIFF(MONTH,bizdate,@var_date) =0  THEN   ISNULL([newVisitNum], 0) + ISNULL([oldVisitNum], 0) ELSE  0 END ) AS 本月到访
                FROM    dbo.s_YHJVisitNum a with(nolock)
                        INNER JOIN [172.16.4.161].highdata_prod.dbo.data_wide_dws_mdm_Project p with(nolock) ON a.[managementProjectGuid] = p.ProjGUID
                WHERE   p.BUGUID = '70DD6DF4-47F7-46AF-B470-BC18EE57D8FF' -- AND   DATEDIFF(DAY, bizdate, @var_date) = 0
				and  p.projguid in (@var_projguid)
                GROUP BY p.ProjGUID
	 ),
-- 数字营销数据
     szyx AS (SELECT    投管编码 AS 项目代码 ,
                        区域 AS 公司事业部 ,
                        营销片区 AS 组团 ,
                        项目GUID ,
                        项目名称 AS 项目名称 ,
                        项目负责人 AS 营销经理 ,
                        存量增量 AS 项目获取状态 ,
                        城市 AS 城市 ,
                        SUM(ISNULL(本日认购金额, 0)) AS 数字营销本日认购 ,
                        SUM(ISNULL(本周认购金额, 0)) AS 数字营销本周认购 ,
                        SUM(ISNULL(本周签约金额, 0)) AS 数字营销本周签约 ,
                        SUM(ISNULL(本月认购金额, 0)) AS 数字营销月度认购 ,
                        SUM(ISNULL(本月签约金额, 0)) AS 数字营销月度签约 ,
                        SUM(ISNULL(本年认购金额, 0)) AS 数字营销年度认购 ,
                        SUM(ISNULL(本年签约金额, 0)) AS 数字营销年度签约
                     FROM   [172.16.4.161].highdata_prod.dbo.s_hnyxxp_projSaleNew sale with(nolock)
                     WHERE  层级 = '组团' AND   层级名称 = '数字营销' AND   DATEDIFF(DAY, 数据清洗日期, @var_date) = 0
					 and sale.项目GUID in (@var_projguid)
              GROUP BY 投管编码 ,
                       区域 ,
                       营销片区 ,
                       项目GUID ,
                       项目名称 ,
                       项目负责人 ,
                       存量增量 ,
                       城市)

-- 查询结果
SELECT  p2.ProjCode 明源项目代码,
        a.* ,
        b.数字营销本日认购 ,
        b.数字营销本周认购 ,
        b.数字营销本周签约 ,
        b.数字营销月度认购 ,
        b.数字营销月度签约 ,
        b.数字营销年度认购 ,
        b.数字营销年度签约,
        ISNULL(lf.本日来访,0) AS 本日来访 ,
        ISNULL(lf.本月到访,0) AS 本月到访
FROM    Sale a
        inner join  dbo.mdm_project p2 on p2.projguid =a.项目GUID 
        LEFT JOIN szyx b ON a.项目GUID = b.项目GUID
		LEFT JOIN lf  ON lf.项目GUID =a.项目GUID