--352数据库
--禁用触发器
ALTER TABLE cb_Contract DISABLE TRIGGER ALL;
ALTER TABLE cb_HTAlter DISABLE TRIGGER ALL;
ALTER TABLE myBusinessUnit DISABLE TRIGGER ALL;
ALTER TABLE cg_CgSolution DISABLE TRIGGER ALL;
ALTER TABLE cg_Contract2CgProc DISABLE TRIGGER ALL;
ALTER TABLE jd_ProjectPlanExecute DISABLE TRIGGER ALL;
