--352数据库
--启用触发器
 ALTER TABLE cb_Contract ENABLE TRIGGER ALL;
 ALTER TABLE cb_HTAlter ENABLE TRIGGER ALL;
 ALTER TABLE myBusinessUnit ENABLE TRIGGER ALL;
 ALTER TABLE cg_CgSolution ENABLE TRIGGER ALL;
 ALTER TABLE cg_Contract2CgProc ENABLE TRIGGER ALL;
 ALTER TABLE jd_ProjectPlanExecute ENABLE TRIGGER ALL;
