--25数据库
--禁用触发器
ALTER TABLE s_Order DISABLE TRIGGER ALL;
ALTER TABLE s_Contract DISABLE TRIGGER ALL;
ALTER TABLE s_Booking DISABLE TRIGGER ALL;
ALTER TABLE s_Opportunity DISABLE TRIGGER ALL;
ALTER TABLE s_Voucher DISABLE TRIGGER ALL;
ALTER TABLE p_room DISABLE TRIGGER ALL;
ALTER TABLE myBusinessUnit DISABLE TRIGGER ALL;
ALTER TABLE k_Task DISABLE TRIGGER ALL;
ALTER TABLE k_Receive DISABLE TRIGGER ALL;
ALTER TABLE k_Pay DISABLE TRIGGER ALL;
