 --25数据库
 --开启触发器
 ALTER TABLE s_Order ENABLE TRIGGER ALL;
 ALTER TABLE s_Contract ENABLE TRIGGER ALL;
 ALTER TABLE s_Booking ENABLE TRIGGER ALL;
 ALTER TABLE s_Opportunity ENABLE TRIGGER ALL;
 ALTER TABLE s_Voucher ENABLE TRIGGER ALL;
 ALTER TABLE p_room ENABLE TRIGGER ALL;
 ALTER TABLE myBusinessUnit ENABLE TRIGGER ALL;
 ALTER TABLE k_Task ENABLE TRIGGER ALL;
 ALTER TABLE k_Receive ENABLE TRIGGER ALL;
 ALTER TABLE k_Pay ENABLE TRIGGER ALL;
